// Angular/dream-property/frontend/src/app/navbar/navbar.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { Emitter } from '../emitters/emitter';
import { ShareidService } from '../services/shareid.service';
import { faHome,faLock ,faUnlock,faUser,faBars,faUserTie} from '@fortawesome/free-solid-svg-icons'
import { FormControl, FormGroup } from '@angular/forms';
import { SearchService } from '../services/search.service';
import { Router } from '@angular/router';
@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  admin =faUserTie
  bars = faBars
  user = faUser
  unlock = faUnlock
  lock = faLock;
  home = faHome;
  authenticated = false;
  adminAuth = false;
  role : any;

  form = new FormGroup({
    search: new FormControl("")
  })

  search = this.form.value.search;
  searchPro(){
    //this.router.navigate([''])
    //console.log(this.form.value.search);
    this.srch.setValue(this.form.value.search)
    this.router.navigate(['/search',this.search]);
  }
  redirect(){
    this.router.navigate(['']);
  }
  constructor(
    private http:HttpClient,
    private shareid : ShareidService,
    private srch : SearchService,
    private router : Router
    ){
    this.role = this.shareid.getRole();
   }

  ngOnInit(): void {

    //alert("navbar called");
    Emitter.authEmitter.subscribe((auth) =>{
      this.authenticated = auth
    })

    Emitter.authAdminEmitter.subscribe((auth) =>{
      this.adminAuth = auth
    })

    this.role = this.shareid.getRole();
    //alert("old Nav :"+this.role)

  }

  logout(){
    const con = confirm('Are you sure you want to logout?')

    if(con === true){
    this.http.post('http://localhost:3031/uview/logout',{},{withCredentials:true})
    .subscribe(() => this.authenticated = false)
    this.shareid.setId(0)
    this.shareid.setRole('user')
  }

  }
}


<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark flex-md-nowrap p-0">
  <a class="navbar-brand" routerLink="">
    <h2> <img src="/assets/logo2.png" width="60" height="60" class="d-inline-block align-top" alt="">
     Dream Property </h2></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto">

      <li class="nav-item active">
        <a class="nav-link" routerLink=""><fa-icon [icon]="home"></fa-icon>
          Home</a>
      </li>
      <!-- <li class="nav-item active">
        <a class="nav-link" routerLink="category"><fa-icon [icon]="bars"></fa-icon>Category</a>
      </li> -->
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle dropend" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <fa-icon [icon]="bars"></fa-icon>Category
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" routerLink="rent">Properties On Rent</a>
            <a class="dropdown-item" routerLink="buy">Properties To Buy</a>
          </div>
      </li>
      <li class="nav-item" *ngIf="!authenticated">
        <a class="nav-link" routerLink="auth"><fa-icon [icon]="unlock"></fa-icon>Login</a>
      </li>

      <li class="nav-item" *ngIf="authenticated">
        <a class="nav-link" routerLink="account"><fa-icon [icon]="user"></fa-icon>My Account</a>
      </li>

      <li class="nav-item" *ngIf="adminAuth && authenticated">
        <a class="nav-link" routerLink="admin"><fa-icon [icon]="admin"></fa-icon>Admin panel</a>
      </li>

      <li class="nav-item" *ngIf="authenticated">
        <a class="nav-link" routerLink="auth" (click)="logout()"><fa-icon [icon]="lock"></fa-icon>
          Logout</a>
      </li>
      &nbsp;&nbsp;&nbsp;
      <form class="form-inline my-2 my-lg-0" [formGroup]="form">
        <span style="display: flex;margin-top: -13px;">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" (change)="redirect()" style="height: 30px;margin-top: 20px;" formControlName="search">
        &nbsp;&nbsp; <button  class="btn btn-outline-light my-3 my-sm-3" routerLink="search/{{form.value.search}}" type="submit">Search</button>
      </span>
    </form>
    </ul>

  </div>

</nav>

// React/dream-property-2.0/frontend/src/components/Header/Navbar.js
import React,{useEffect} from 'react'
import logo from '../../logo.png'
import { Link } from 'react-router-dom'
import {userAuthenticated,logoutUser} from '../../redux/actions/userActions'
import {fetchProperties} from '../../redux/actions/propertyActions'
import { useDispatch,useSelector} from 'react-redux'
import { useNavigate  } from 'react-router-dom';
// import CreateCon from '../../util/CreatContext'

const Navbar = () => {
    const navigate = useNavigate();
    const dispatch = useDispatch()
   
    console.log('navbar called');

    const loggedUser = useSelector((state) => state.loginUser.loggedInUser)
    var loggedAdmin = useSelector((state) => state.loginUser.admin)

    console.log('logged admin',loggedAdmin);

    //const userData = useSelector((state) => state.loginUser.auth)
    console.log(loggedUser);
   
    var flag = false;
    var loginFlag = false;
   
    const logUser = localStorage.getItem('login')
    if(logUser === 'false'){
      loginFlag=false
    }else{
      loginFlag = true;
    }
    console.log('log user:',logUser);

        if(localStorage.getItem('user')){
          
          const data = localStorage.getItem('user')
          const obj = JSON.parse(data)
          const role = obj.role;

          if(role === 'admin'){
            flag = true;
            //loggedAdmin = true
          }
        }
        else{
          flag = false;
        }
   console.log(flag); 
  // useEffect(()=>{
  //   //dispatch(fetchProperties());
  //     dispatch(userAuthenticated());
  //     // eslint-disable-next-line react-hooks/exhaustive-deps
  // },[loginFlag])
  
  const handleLogout = () => {
    dispatch(logoutUser());
    localStorage.removeItem('user')
    localStorage.setItem('login',false)
    navigate('/login')
  }

  console.log('logged admin',loggedAdmin);
  return (
    <div>
            <nav className='navbar navbar-expand-lg navbar-light fixed-top bg-light flex-md-nowrap p-0'>

{/* <nav className="navbar sticky-top fixed-top navbar-expand-lg navbar-light bg-light flex-md-nowrap p-0"> */}
  <Link className="navbar-brand" to=""><h2 style={{fontFamily:'monospace'}}> <img src={logo} width="40" height="40" class="d-inline-block align-top" alt="img" />
     Dream Property </h2></Link>
  <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span className="navbar-toggler-icon"></span>
  </button>

  <div className="collapse navbar-collapse" id="navbarSupportedContent">
    <ul className="navbar-nav ms-auto" style={{marginRight:'20px'}}>

     { !flag ? ( <><li className="nav-item active">
        <Link className="nav-link" to="home">Home</Link>
      </li>
      <li className="nav-item dropdown">
        <Link className="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Category
        </Link>
        <div className="dropdown-menu col-md-5" aria-labelledby="navbarDropdown" >
          <Link className="dropdown-item" to="/rent">Properties On Rent</Link>
          <Link className="dropdown-item" to="/buy">Properties To Buy</Link>
        </div>
      </li>
      </> ) :
      (<></>) 
  }
      {flag ? (
        <>
      <li className="nav-item active">
        <Link className="nav-link" to="/admin/properties">All Properties</Link>
      </li>
     
      
      <li className="nav-item active">
        <Link className="nav-link" to="/admin/add-property">Add Property</Link>
      </li>

      <li className="nav-item active">
        <Link className="nav-link" to="/admin/inquiries">All Inquiries</Link>
      </li>
      </>
      ) : (
        <span></span>
      ) }
      
      {/*  <li className="nav-item active">
        <Link className="nav-link" to="login">Login</Link>
      </li>
       <li className="nav-item active" onClick={handleLogout}>
        <Link className="nav-link">Logout</Link>
      </li> 
      */}
      {loggedUser && !flag ? (<li className="nav-item active">
        <Link className="nav-link" to='inq-properties'>Inquired Properties</Link>
      </li>) : (<></>)}
      {loggedUser  ? (
      <>
      <li className="nav-item active">
        <Link className="nav-link" to='profile'>Profile</Link>
      </li>
      <li className="nav-item active" onClick={handleLogout}>
        <Link className="nav-link">Logout</Link>
      </li>
      </> ) : (
        <li className="nav-item active">
        <Link className="nav-link" to="login">Login</Link>
      </li>
      ) }  
      
    </ul>
  
  </div>
</nav>
<br/><br/><br/><br/>
    </div>
  )
}


export default Navbar
